### ISSUE TITLE
我这里报错显示没有启动js，请问该如何解决呢？We're sorry but movie-sync doesn't work properly without JavaScript enabled. Please enable it to continue

### ISSUE THREAD

**Issue by saladcat** [VaalaCat/movie-sync#2]
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/movie/favicon.ico"><title>movie-sync</title><script defer="defer" src="/movie/js/chunk-vendors.95798e1d.js" type="module"></script><script defer="defer" src="/movie/js/app.e8b1ee51.js" type="module"></script><link href="/movie/css/chunk-vendors.a1f70f1f.css" rel="stylesheet"><link href="/movie/css/app.8049d3cb.css" rel="stylesheet"><script defer="defer" src="/movie/js/chunk-vendors-legacy.d4e3bc8c.js" nomodule></script><script defer="defer" src="/movie/js/app-legacy.5525a4f9.js" nomodule></script></head><body><noscript><strong>We're sorry but movie-sync doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div></body></html>

We're sorry but movie-sync doesn't work properly without JavaScript enabled. Please enable it to continue

**Comment by VaalaCat** [comment]
可能是浏览器没有启动js,chrome的话按下f12进入开发者模式,然后按下f1,找到Disable JavaScript,如果打勾了就取消掉
