### ISSUE TITLE
运行后端后打开网页白屏，F12显示报错

### ISSUE THREAD

**Issue by xxd666** [VaalaCat/movie-sync#3]
[TimeHooker] loading outer window...
key:  {"type":"domain","url":"127.0.0.1:8000"}
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
Time Hooker Works!
Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by VaalaCat** [comment]
发布了新的docker版，可以重新试试

**Comment by VaalaCat** [comment]
Too long without updating the issue status, closing the issue.
